services:
  db:
    image: postgres:16
    container_name: internship_pg
    restart: unless-stopped
    environment:
      POSTGRES_DB: internshipdb
      POSTGRES_USER: internshipuser
      POSTGRES_PASSWORD: supersecret
    ports:
      - "5432:5432"
    volumes:
      - internship_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U internshipuser -d internshipdb"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
  internship_data: